### ISSUE TITLE
Could you migrate to Fluentd v0.14 API?

### ISSUE THREAD

**Issue by okkez** [nulab/fluent-plugin-typetalk#5]
Could you migrate to Fluent d v0.14 API?

* Pros/Cons
  * https://www.clear-code.com/blog/2017/5/23.html (ja)
  * https://gist.github.com/okkez/05ee6af7b8bb7de852a36eb2f679c344 (en)
* Updating plugin for v0.14 from v0.12
  * http://docs.fluentd.org/v0.14/articles/plugin-update-from-v12

Other chat(like) services:
* fluent-plugin-hipchat: done
* fluent-plugin-slack: will be merged soon
* fluent-plugin-twitter: done

And 100+ plugins have already been migrated to Fluentd v0.14 plugin API.

Mention me, please. If you have questions.

**Comment by tsuyoshizawa** [comment]
We are going to migrate to Fluentd v0.14.
We understand we use Ruby 1.x that version is already deprecated on current plugin.

We will make time to migrate plugin. (Or someone can give us the PR)

**Comment by tsuyoshizawa** [comment]
@okkez 

I made PR to support fluentd v0.14.
Thank you for your help.

If you have any suggestions, let me know.
I am going to release new version.

**Comment by okkez** [comment]
OK, I will check the PR later. Thanks!

**Comment by tsuyoshizawa** [comment]
Thank you for your help.
We released version 0.1.0 with supporting fluentd v0.14.

**Comment by okkez** [comment]
Thank you for migrating plugin!
