### ISSUE TITLE
Tag v0.10 is missing

### ISSUE THREAD

**Issue by okkez** [nulab/fluent-plugin-typetalk#7]
Could you tag v0.1.0?

**Comment by tsuyoshizawa** [comment]
Oh, I'm sorry.
I have forgotten to push the tag before I pushed a commit as release.

v0.1.0 is now tagged. 
https://github.com/nulab/fluent-plugin-typetalk/tree/v0.1.0

Thank you for your notification.

**Comment by okkez** [comment]
Thank you for quick response!
